---
datacenter:
  children:
    routers:
      hosts:
        192.168.0.109:
       vars:
         testvar: 999
  vars:
    ansible_connection: network_cli
    ansible_network: ios
    ansible_user: admin
    ansible_ssh_pass: cisco
